// <auto-generated />
using System;
using EmployeeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Date");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EmployeeApi.Models.BookingParticipant", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "EmployeeId");

                    b.ToTable("BookingParticipants");
                });

            modelBuilder.Entity("EmployeeApi.Models.MeetingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("MeetingRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Equipment = "პროექტორი;ეკრანი;კონფერენც ტელეფონი;თეთრი დაფა;Wi-Fi",
                            Location = "IV სართული",
                            Name = "შეხვედრის ოთახი ცენტრალური",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 12,
                            Equipment = "TV ეკრანი;ფლიპჩარტი;Wi-Fi",
                            Location = "III სართული",
                            Name = "შეხვედრის ოთახი სატვირთო",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            Equipment = "პროექტორი;მიკროფონი;დინამიკები;სასწავლო მაგიდები;Wi-Fi",
                            Location = "II სართული",
                            Name = "სასწავლო ცენტრი",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 6,
                            Equipment = "კამერა;განათება;მიკროფონი;ხმის ჩამწერი",
                            Location = "I სართული",
                            Name = "სტუდია",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 60,
                            Equipment = "სცენა;ხმის სისტემა;პროექტორი;სავარძლები",
                            Location = "ცოკოლი",
                            Name = "კლუბი",
                            RequiresApproval = true
                        });
                });

            modelBuilder.Entity("EmployeeApi.Models.Booking", b =>
                {
                    b.HasOne("EmployeeApi.Models.MeetingRoom", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeApi.Models.BookingParticipant", b =>
                {
                    b.HasOne("EmployeeApi.Models.Booking", null)
                        .WithMany("Participants")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeApi.Models.Booking", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
